config/routes.rb
Gerador2::Application.routes.draw do

  resources :turmas do
    resources :horarios
  end

  resources :grade_restricos do
    resources :professors
  end

  resources :disciplinas do
    resources :slot
  end

  resources :professors do
    resources :slot
  end

  resources :slots do
    resources :horarios
  end

  resources :horarios do
    resources :turmas
    resources :grades
    resources :grade_restricos
  end

  resources :grades do
    get :gera_nova_grade
    resources :turmas
  end

  match 'home'=>'grades#index'

  match 'nova_turma' => 'turmas#index'

  match 'novo_professor' =>'professors#index'

  match 'nova_disciplina' =>'disciplinas#index'

  match 'novo_slot' => 'slots#index'

  match 'novo_horario' =>'horarios#index'

  match 'nova_grade' =>'grades#index'

  match 'gera_grade' =>'grades#gera_grade'

end

app/models/slot.rb
# == Schema Information
#
# Table name: slots
#
#  id            :integer          not null, primary key
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  horario_id    :integer
#  disciplina_id :integer
#  professor_id  :integer
#

class Slot < ActiveRecord::Base

  attr_accessible :disciplina_id ,:professor_id, :horario_id

  has_many :horario

  has_one :professor,
  		    :class_name => "Professor",
  		    :foreign_key => 'id',
          :dependent => :destroy

  has_one :disciplina,
  		    :class_name => "Disciplina",
  		    :foreign_key => 'id',
          :dependent => :destroy

  #validates_presence =>:professor_id, :disciplina_id


  #validates_presence_of :disciplina, :professor

  after_create :atualiza_slot_id_quando_criado_agendamento

  def atualiza_slot_id_quando_criado_agendamento

    p = Professor.find_by_id(self.professor_id)
    p.slot_id = self.id
  end


end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @slots }
    end
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
    @slot = Slot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slot }
    end
  end

  # GET /slots/new
  # GET /slots/new.json
  def new
    @slot = Slot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slot }
    end
  end

  # GET /slots/1/edit
  def edit
    @slot = Slot.find(params[:id])
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(params[:slot])

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Agendamento criado com sucesso.' }
        format.json { render json: @slot, status: :created, location: @slot }
      else
        format.html { render action: "new" }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /slots/1
  # PUT /slots/1.json
  def update
    @slot = Slot.find(params[:id])

    respond_to do |format|
      if @slot.update_attributes(params[:slot])
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot = Slot.find(params[:id])
    @slot.destroy

    respond_to do |format|
      format.html { redirect_to slots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/slots/_form.html.erb
<%= form_for(@slot) do |f| %>
  <% if @slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% @slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professor %><br />
    <% @todos_professores= Professor.all.map{|p| [ p.nome_professor, p.id]} %>
    <%= f.select(:professor_id,@todos_professores) %>
    <%# options_from_collection_for_select(Professor.all, :id, :professor) %>
  </div>
    </br>
  <div class="field">
    <%= f.label :disciplina %><br />
    <% @todas_disciplinas = Disciplina.all.map{|p| [ p.nome_disciplina, p.id]} %>
    <%= f.select(:disciplina_id,@todas_disciplinas) %>
    <%# options_from_collection_for_select(Disciplina.all, :id, :disciplina) %>
  </div>
    </br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<h1>Agendamentos </h1>
<h4> Cada professor é associado a uma ou mais disciplinas</h4>

<table>
  <tr>
    <th>Professor</th>
    <th>Disciplina</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slots.each do |slot| %>
  <tr>
    <% @slot_prof = slot.professor_id %>
    <% @slot_disc = slot.disciplina_id %>
    <td><%= Professor.find_by_id(@slot_prof).nome_professor %> </td>
    <td><%= Disciplina.find_by_id(@slot_disc).nome_disciplina %> </td>
    <td><%= link_to 'Show', slot %></td>
    <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
    <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<h4> Para atribuir um profesor a uma disciplina</h4>
<%= link_to 'Adicionar', new_slot_path %>

app/views/slots/new.html.erb
<h1>New slot</h1>

<%= render 'form' %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<% @slots = Slot.all %>
<% @slots.each do |slot| %>
    <tr>
      <% @slot_prof = slot.professor_id %>
      <% @slot_disc = slot.disciplina_id %>
    </tr>
<% end %>
<p>
  <b>Professor:</b>
  <% @nome_prof = Professor.find_by_id(@slot_prof).nome_professor %>
  <%= @nome_prof %>
</p>

<p>
  <b>Disciplina:</b>
  <% @nome_disc = Disciplina.find_by_id(@slot_disc).nome_disciplina %>
  <%= @nome_disc %>

</p>


<%= link_to 'Editar', edit_slot_path(@slot) %>
<%= link_to 'Volta', slots_path %>