config/routes.rb
Gerador2::Application.routes.draw do

  resources :turmas do
    resources :horarios
  end

  resources :grade_restricos do
    resources :professors
  end

  resources :disciplinas do
    resources :slot
  end

  resources :professors do
    resources :slot
  end

  resources :slots do
    resources :horarios
  end

  resources :horarios do
    resources :turmas
    resources :grades
    resources :grade_restricos
  end

  resources :grades do
    get :gera_nova_grade
    resources :turmas
  end

  match 'home'=>'grades#index'

  match 'nova_turma' => 'turmas#index'

  match 'novo_professor' =>'professors#index'

  match 'nova_disciplina' =>'disciplinas#index'

  match 'novo_slot' => 'slots#index'

  match 'novo_horario' =>'horarios#index'

  match 'nova_grade' =>'grades#index'

  match 'gera_grade' =>'grades#gera_grade'

end

app/models/grade_restrico.rb
# == Schema Information
#
# Table name: grades
#
#  id                     :integer          not null, primary key
#  num_periodos_dia       :integer          default(5)
#  tempo_cada_periodo     :time
#  turma_id               :string(255)      default("generica")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  hora_de_inicio_da_aula :time
#  score_solucao          :integer
#

class GradeRestrico <Grade #< ActiveRecord::Base

  attr_accessible :nome_professor_id, :vetor_restricoes

  belongs_to :professor

  @vetor_restricoes = []
=begin
  def initialize(professor)
  	:nome_professor = professor || 'anonimo'
  end
=end
end

app/controllers/grade_restricos_controller.rb
class GradeRestricosController < ApplicationController
  # GET /grade_restricos
  # GET /grade_restricos.json
  def index
    @grade_restricos = GradeRestrico.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grade_restricos }
    end
  end

  # GET /grade_restricos/1
  # GET /grade_restricos/1.json
  def show
    @grade_restrico = GradeRestrico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grade_restrico }
    end
  end

  # GET /grade_restricos/new
  # GET /grade_restricos/new.json
  def new
    @grade_restrico = GradeRestrico.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grade_restrico }
    end
  end

  # GET /grade_restricos/1/edit
  def edit
    @grade_restrico = GradeRestrico.find(params[:id])
  end

  # POST /grade_restricos
  # POST /grade_restricos.json
  def create
    @grade_restrico = GradeRestrico.new(params[:grade_restrico])

    respond_to do |format|
      if @grade_restrico.save
        format.html { redirect_to @grade_restrico, notice: 'Grade restrico was successfully created.' }
        format.json { render json: @grade_restrico, status: :created, location: @grade_restrico }
      else
        format.html { render action: "new" }
        format.json { render json: @grade_restrico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grade_restricos/1
  # PUT /grade_restricos/1.json
  def update
    @grade_restrico = GradeRestrico.find(params[:id])

    respond_to do |format|
      if @grade_restrico.update_attributes(params[:grade_restrico])
        format.html { redirect_to @grade_restrico, notice: 'Grade restrico was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grade_restrico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grade_restricos/1
  # DELETE /grade_restricos/1.json
  def destroy
    @grade_restrico = GradeRestrico.find(params[:id])
    @grade_restrico.destroy

    respond_to do |format|
      format.html { redirect_to grade_restricos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/grade_restricos_helper.rb
module GradeRestricosHelper
end

app/views/grade_restricos/_form.html.erb
<%= form_for(@grade_restrico) do |f| %>
  <% if @grade_restrico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade_restrico.errors.count, "error") %> prohibited this grade_restrico from being saved:</h2>

      <ul>
      <% @grade_restrico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_professor %><br />
    <% @nomes_de_profes = Professor.all.map{|cada|[cada.nome_professor, cada.id]}%>
    <%= select_tag(:nome_professor_id, options_for_select(@nomes_de_profes)) %>
  </div>
  <div>
    <p>
    Escolha entre 0, 1 , 2 ou 3 conforme o nível de restrição
    Sendo 0 - nenhuma restrição
          1 - restrição baixa
          2 - restrição média
          3 - restrição alta
    </p>
  </div>

    <div class="grade em si">

    <table>
      <% dias_da_semana.each {|feira| %>
      <th><%= dias_da_semana} %>  </th>
      <% tam_grade = Grade.num_periodos_dia %>
      <tr> </tr>

      <%= %>
    </table>



  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grade_restricos/edit.html.erb
<h1>Editing grade_restrico</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade_restrico %> |
<%= link_to 'Back', grade_restricos_path %>

app/views/grade_restricos/index.html.erb
<h1>Listing grade_restricos</h1>

<table>
  <tr>
    <th>Nome professor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grade_restricos.each do |grade_restrico| %>
  <tr>
    <td><%= grade_restrico.nome_professor %></td>
    <td><%= link_to 'Show', grade_restrico %></td>
    <td><%= link_to 'Edit', edit_grade_restrico_path(grade_restrico) %></td>
    <td><%= link_to 'Destroy', grade_restrico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grade restrico', new_grade_restrico_path %>

app/views/grade_restricos/new.html.erb
<h1>New grade_restrico</h1>

<%= render 'form' %>

<%= link_to 'Back', grade_restricos_path %>

app/views/grade_restricos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome professor:</b>
  <%= @grade_restrico.nome_professor %>
</p>


<%= link_to 'Edit', edit_grade_restrico_path(@grade_restrico) %> |
<%= link_to 'Back', grade_restricos_path %>