config/routes.rb
Gerador2::Application.routes.draw do

  resources :turmas do
    resources :horarios
  end

  resources :grade_restricos do
    resources :professors
  end

  resources :disciplinas do
    resources :slot
  end

  resources :professors do
    resources :slot
  end

  resources :slots do
    resources :horarios
  end

  resources :horarios do
    resources :turmas
    resources :grades
    resources :grade_restricos
  end

  resources :grades do
    get :gera_nova_grade
    resources :turmas
  end

  match 'home'=>'grades#index'

  match 'nova_turma' => 'turmas#index'

  match 'novo_professor' =>'professors#index'

  match 'nova_disciplina' =>'disciplinas#index'

  match 'novo_slot' => 'slots#index'

  match 'novo_horario' =>'horarios#index'

  match 'nova_grade' =>'grades#index'

  match 'gera_grade' =>'grades#gera_grade'

end

app/models/professor.rb
# == Schema Information
#
# Table name: professors
#
#  id                  :integer          not null, primary key
#  nome_professor      :string(255)
#  grade_restricoes_id :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  slot_id             :integer
#

class Professor < ActiveRecord::Base

  attr_accessible :nome_professor, :slot_id

  belongs_to :slot

end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @professors }
    end
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @professor = Professor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @professor }
    end
  end

  # GET /professors/new
  # GET /professors/new.json
  def new
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @professor }
    end
  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render json: @professor, status: :created, location: @professor }
      else
        format.html { render action: "new" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /professors/1
  # PUT /professors/1.json
  def update
    @professor = Professor.find(params[:id])

    respond_to do |format|
      if @professor.update_attributes(params[:professor])
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to professors_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_professor %><br />
    <%= f.text_field :nome_professor %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editando professor</h1>

<%= render 'form' %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<h1>Cadastro de professores</h1>

<table>
  <tr>
    <th>Nome professor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td><%= professor.nome_professor %></td>
    <td><%= link_to 'Show', professor %></td>
    <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
    <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Deseja realmente excluir esse registro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>Cadastrar professor</h1>

<%= render 'form' %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome professor:</b>
  <%= @professor.nome_professor %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>