config/routes.rb
Gerador2::Application.routes.draw do

  resources :turmas do
    resources :horarios
  end

  resources :grade_restricos do
    resources :professors
  end

  resources :disciplinas do
    resources :slot
  end

  resources :professors do
    resources :slot
  end

  resources :slots do
    resources :horarios
  end

  resources :horarios do
    resources :turmas
    resources :grades
    resources :grade_restricos
  end

  resources :grades do
    get :gera_nova_grade
    resources :turmas
  end

  match 'home'=>'grades#index'

  match 'nova_turma' => 'turmas#index'

  match 'novo_professor' =>'professors#index'

  match 'nova_disciplina' =>'disciplinas#index'

  match 'novo_slot' => 'slots#index'

  match 'novo_horario' =>'horarios#index'

  match 'nova_grade' =>'grades#index'

  match 'gera_grade' =>'grades#gera_grade'

end

app/views/layouts/application.html.erb
<html>
<head>
  <title>Gerador de horários ver. 1.2</title>

  <h1 id="titulo">Gerador de horários</h1>
  <%= stylesheet_link_tag    "bootstrap.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home",home_path %>
<%= link_to "Turmas", nova_turma_path %>
<%= link_to "Professores", novo_professor_path %>
<%= link_to "Disciplinas",nova_disciplina_path %>
<%= link_to "Atribuicoes", novo_slot_path %>
<%= link_to "Horarios ", novo_horario_path %>
<%= yield %>

<div class="container">
  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-9">
      <div class="row">
        <div class="col-xs-6">
          <div class="row">
            <div class="col-xs-6"></div>
            <div class="col-xs-6"></div>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="row">
            <div class="col-xs-6"></div>
            <div class="col-xs-6"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>